sudo: required
dist: trusty
before_cache:
  - rm -f  $HOME/.m2/settings.xml
  - rm -rf $HOME/.m2/repository/org/testng/testng-remote*
  - rm -rf $HOME/.groovy/grapes/org.testng.testng-remote
cache:
  directories:
    - $HOME/.m2
    - $HOME/.groovy/grapes
language: java
jdk:
  - oraclejdk9
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install: 
  - export MAVEN_SKIP_RC=true
  - export JAVA_VER=$(java -version 2>&1 | grep -i version | cut -d'"' -f2 | cut -d'.' -f1-2)
  - echo "JAVA_VER=$JAVA_VER"

install: echo "skip 'mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V' step"

script:
  - mkdir -p ~/.groovy
  - cp -f remote-test/src/test/resources/grapeConfig.xml ~/.groovy
  - mkdir -p ~/.m2
  - cp -f dist/settings.xml ~/.m2
  - sed -i -e "s/BINTRAY_USER/${BINTRAY_USER}/g" -e "s/BINTRAY_API_KEY/${BINTRAY_API_KEY}/g" ~/.m2/settings.xml
  - if [[ "$JAVA_VER" == "9-ea" ]]; then mvn -e -DskipIntTest=false clean install jacoco:report; else mvn -e -DskipIntTest=false clean install jacoco:report coveralls:report; fi

after_success:
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]] && [[ ${TRAVIS_BRANCH} == "master" ]]; then mvn -e deploy; fi
